name: CI

on: [push, pull_request]

jobs:
  perl-versions:
    runs-on: ubuntu-latest
    name: List Perl versions
    outputs:
      perl-versions: ${{ steps.action.outputs.perl-versions }}
    steps:
      - id: action
        uses: perl-actions/perl-versions@v1
        with:
          since-perl: v5.8
          with-devel: true
  test:
    needs:
      - perl-versions
    strategy:
      fail-fast: false
      matrix:
        perl-version: ${{ fromJson (needs.perl-versions.outputs.perl-versions) }}

    runs-on: ubuntu-latest
    name: perl ${{matrix.perl-version}}
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
    - uses: actions/checkout@v4
    - name: Show perl version
      run: |
        perl -v
    - name: Install modules
      run: |
        cpanm --installdeps .
    - name: Build module and execute tests
      env:
        AUTHOR_TESTING: 1
        RELEASE_TESTING: 1
      run: |
        perl Makefile.PL
        make
        make test
